export type EventCategory =
  | 'follow-set'
  | 'emoji-set'
  | 'group'
  | 'chat-message'
  | 'note'
  | 'thread'
  | 'long-form-content'
  | 'poll'
  | 'code-snippet'
  | 'picture'
  | 'video'
  | 'live-stream'
  | 'highlight'
  | 'git-repo'
  | 'community'
  | 'app-recommendation';
